"""JIT-on-first-use dispatcher for causal_conv1d bwd_full.

Each unique runtime config (dtype × n_elts × width × has_bias ×
has_seq_idx × has_initial_states × apply_silu × contig_inner ×
aligned_seq) lazily generates a tiny single-variant ``.mojo`` file at
call time, compiles it via ``mojo build``, and caches the resulting
``.so`` on disk.

Shared codegen + compile + load + cache plumbing lives in
``causal_conv1d_mojo._jit_common``.

Performance note (AMD-specific): The Mojo `DeviceContext()`
constructor issues `hipStreamCreate` and the matching `__del__`
issues `hipStreamDestroy`. At small-batch shapes the bwd kernel is
only ~6-10 us of GPU work, so per-call stream churn shows up in
torch.profiler. Each variant exposes a
``causal_conv1d_bwd_full_acquire_ctx`` entry point; the first call
from Python invokes it to obtain a process-lifetime DeviceContext
handle (refcount-retained so the wrapper destructor is a no-op), and
caches it. Subsequent dispatches pass that handle in to
`launch_bwd_full`, which wraps it via the doc-hidden non-owning
constructor — no new hipStream per call.
"""

from __future__ import annotations

from functools import lru_cache
from pathlib import Path

from causal_conv1d_mojo._jit_common import compile_and_load_variant

_BWD_DIR = Path(__file__).resolve().parent
_CTX_MOJO = _BWD_DIR.parent / "_ctx.mojo"

_DTYPE_NAME = {0: "fp16", 1: "bf16", 2: "fp32"}
_DTYPE_EXPR = {0: "DType.float16", 1: "DType.bfloat16", 2: "DType.float32"}

# Wide per-thread element count (16-byte LDG): 8 for fp16/bf16, 4 for
# fp32. Mirrors `kNEltsBwd_for` in bwd_full/common.mojo.
_KN_ELTS_WIDE = {0: 8, 1: 8, 2: 4}
_KN_ELTS_NARROW = 4
# Block size (`kNThreads` in bwd_full/common.mojo).
_KNTHREADS = 128


def call_bwd_full(args: tuple) -> None:
    """JIT-compile (if needed) and dispatch a single bwd_full call."""
    variant_fn, ctx_handle = _get_variant_fn(_config_from_args(args))
    # Tack ctx_handle on as the 41st positional arg — the variant
    # entry point destructures `args[40]` for it. (args[39] is the
    # `use_external_stream` flag, already baked into the variant's
    # comptime params.)
    variant_fn(*args, ctx_handle)


def _config_from_args(args: tuple) -> tuple:
    dtype_code = args[23]
    width = args[25]
    has_bias = bool(args[21])
    apply_silu = bool(args[22])
    has_seq_idx = bool(args[26])
    has_initial_states = bool(args[30])
    seqlen = args[9]
    contig_inner = (
        args[12] == 1  # x_l_stride
        and args[14] == 1  # w_w_stride
        and args[17] == 1  # dout_l_stride
        and args[20] == 1  # dx_l_stride
    )

    # Match the original dispatcher's runtime n_elts pick: wide only if
    # (a) wide differs from narrow (i.e. dtype is 16-bit) and (b) seqlen
    # is aligned to kNThreads * wide. Else narrow (4).
    n_elts_wide = _KN_ELTS_WIDE[dtype_code]
    use_wide = (
        n_elts_wide != _KN_ELTS_NARROW and (seqlen % (_KNTHREADS * n_elts_wide)) == 0
    )
    n_elts = n_elts_wide if use_wide else _KN_ELTS_NARROW
    aligned_seq = (seqlen % (_KNTHREADS * n_elts)) == 0
    # See fwd/_jit.py for why this is comptime instead of a runtime
    # branch on `stream_handle_addr`. Python wrapper sets 1 for CUDA,
    # 0 for Metal.
    use_external_stream = bool(args[39])

    return (
        dtype_code,
        n_elts,
        width,
        has_bias,
        has_seq_idx,
        has_initial_states,
        apply_silu,
        contig_inner,
        aligned_seq,
        use_external_stream,
    )


def _mod_name(config: tuple) -> str:
    (dt, ne, w, hb, hs, hi, silu, c, a, ues) = config
    return (
        f"{_DTYPE_NAME[dt]}_n{ne}_w{w}"
        f"_hb{int(hb)}_hs{int(hs)}_hi{int(hi)}_silu{int(silu)}"
        f"_contig{int(c)}_aligned{int(a)}_extstr{int(ues)}"
    )


@lru_cache(maxsize=None)
def _get_variant_fn(config: tuple):
    import sys

    mod_name = _mod_name(config)
    fn = compile_and_load_variant(
        subpkg="bwd_full",
        source_dir=_BWD_DIR,
        shared_files=("kernel.mojo", "common.mojo", "launch.mojo", _CTX_MOJO),
        mod_name=mod_name,
        variant_source=_generate_variant_source(mod_name, config),
        entry_point_name="causal_conv1d_bwd_full_variant",
    )
    # The shared loader stashes the loaded variant module in
    # sys.modules so we can grab the one-shot ctx-handle helper without
    # re-importing the .so.
    module = sys.modules[mod_name]
    acquire = getattr(module, "causal_conv1d_bwd_full_acquire_ctx")
    ctx_handle = int(acquire(()))
    return fn, ctx_handle


def _generate_variant_source(mod_name: str, config: tuple) -> str:
    (
        dtype_code,
        n_elts,
        width,
        has_bias,
        has_seq_idx,
        has_initial_states,
        apply_silu,
        contig_inner,
        aligned_seq,
        use_external_stream,
    ) = config
    return f'''\
"""JIT-generated variant for causal_conv1d_bwd_full (config-frozen).

Generated by causal_conv1d_mojo.bwd_full._jit; do not hand-edit.
Module: {mod_name}
"""

from std.os import abort
from std.python import PythonObject
from std.python.bindings import PythonModuleBuilder

from launch import launch_bwd_full
from _ctx import acquire_ctx_handle


def causal_conv1d_bwd_full_acquire_ctx(
    mut py_self: PythonObject,
    mut args: PythonObject,
) raises -> PythonObject:
    """Create + retain a process-lifetime DeviceContext.

    Called once per variant from the Python side; the returned address
    is reused for every subsequent `causal_conv1d_bwd_full_variant`
    call to avoid `hipStreamCreate`/`Destroy` per launch.
    """
    var addr: Int = acquire_ctx_handle()
    return PythonObject(addr)


def causal_conv1d_bwd_full_variant(
    mut py_self: PythonObject,
    mut args: PythonObject,
) raises -> PythonObject:
    var x_addr: Int = Int(py=args[0])
    var w_addr: Int = Int(py=args[1])
    var b_addr: Int = Int(py=args[2])
    var dout_addr: Int = Int(py=args[3])
    var dx_addr: Int = Int(py=args[4])
    var dweight_acc_addr: Int = Int(py=args[5])
    var dbias_acc_addr: Int = Int(py=args[6])
    var batch_int: Int = Int(py=args[7])
    var dim_int: Int = Int(py=args[8])
    var seqlen_int: Int = Int(py=args[9])
    var x_b_stride: Int = Int(py=args[10])
    var x_c_stride: Int = Int(py=args[11])
    var x_l_stride: Int = Int(py=args[12])
    var w_c_stride: Int = Int(py=args[13])
    var w_w_stride: Int = Int(py=args[14])
    var dout_b_stride: Int = Int(py=args[15])
    var dout_c_stride: Int = Int(py=args[16])
    var dout_l_stride: Int = Int(py=args[17])
    var dx_b_stride: Int = Int(py=args[18])
    var dx_c_stride: Int = Int(py=args[19])
    var dx_l_stride: Int = Int(py=args[20])
    var stream_handle_addr: Int = Int(py=args[24])
    var seq_idx_addr: Int = Int(py=args[27])
    var seq_idx_b_stride: Int = Int(py=args[28])
    var seq_idx_l_stride: Int = Int(py=args[29])
    var initial_states_addr: Int = Int(py=args[31])
    var initial_states_b_stride: Int = Int(py=args[32])
    var initial_states_c_stride: Int = Int(py=args[33])
    var initial_states_l_stride: Int = Int(py=args[34])
    var dinitial_states_addr: Int = Int(py=args[35])
    var dinitial_states_b_stride: Int = Int(py=args[36])
    var dinitial_states_c_stride: Int = Int(py=args[37])
    var dinitial_states_l_stride: Int = Int(py=args[38])
    # args[39] is `use_external_stream` (baked into comptime params);
    # ctx_handle is appended as args[40] by `call_bwd_full`.
    var ctx_handle_addr: Int = Int(py=args[40])

    if batch_int == 0 or dim_int == 0 or seqlen_int == 0:
        return PythonObject(None)

    launch_bwd_full[
        {_DTYPE_EXPR[dtype_code]},
        {n_elts},
        {width},
        {has_bias},
        {has_seq_idx},
        {has_initial_states},
        {apply_silu},
        {contig_inner},
        {aligned_seq},
        {use_external_stream},
    ](
        batch_int,
        dim_int,
        seqlen_int,
        x_addr,
        w_addr,
        b_addr,
        dout_addr,
        dx_addr,
        dweight_acc_addr,
        dbias_acc_addr,
        seq_idx_addr,
        initial_states_addr,
        dinitial_states_addr,
        x_b_stride,
        x_c_stride,
        x_l_stride,
        w_c_stride,
        w_w_stride,
        dout_b_stride,
        dout_c_stride,
        dout_l_stride,
        dx_b_stride,
        dx_c_stride,
        dx_l_stride,
        seq_idx_b_stride,
        seq_idx_l_stride,
        initial_states_b_stride,
        initial_states_c_stride,
        initial_states_l_stride,
        dinitial_states_b_stride,
        dinitial_states_c_stride,
        dinitial_states_l_stride,
        stream_handle_addr,
        ctx_handle_addr,
    )
    return PythonObject(None)


@export
def PyInit_{mod_name}() -> PythonObject:
    try:
        var m = PythonModuleBuilder("{mod_name}")
        m.def_py_function[causal_conv1d_bwd_full_variant]("causal_conv1d_bwd_full_variant")
        m.def_py_function[causal_conv1d_bwd_full_acquire_ctx]("causal_conv1d_bwd_full_acquire_ctx")
        return m.finalize()
    except e:
        abort(String("failed to create Python module: ", e))
'''
