"""JIT-on-first-use dispatcher for causal_conv1d update (single-step
state update + conv output).

Each unique runtime config (dtype × width × has_bias × apply_silu ×
has_state_indices × is_circular) lazily generates a tiny single-variant
``.mojo`` file at call time, compiles it via ``mojo build``, and caches
the resulting ``.so`` on disk.

Shared codegen + compile + load + cache plumbing lives in
``causal_conv1d_mojo._jit_common``.

Performance note (AMD-specific): The Mojo `DeviceContext()` constructor
calls `hipStreamCreate` under the hood, and the matching `__del__`
calls `hipStreamDestroy`. At decode shapes the update kernel is only
~3 us of GPU work, so a per-call stream churn (1 ms+ on the CPU side)
dwarfs everything else — every iteration shows up as a pair of
`hipStreamCreate`/`Destroy` calls in the torch.profiler trace, and on
the GPU side rocprof reports ~5 us per kernel vs ~3 us for upstream.

To avoid this, each variant exposes a `causal_conv1d_update_acquire_ctx`
entry point. The first call from Python invokes it to obtain a
process-lifetime DeviceContext handle (refcount-retained so the wrapper
destructor is a no-op), and caches it. Subsequent dispatches pass that
handle in to `launch_update`, which wraps it via the doc-hidden
non-owning constructor — no new hipStream is created per call.
"""

from __future__ import annotations

from functools import lru_cache
from pathlib import Path

from causal_conv1d_mojo._jit_common import compile_and_load_variant

_UPDATE_DIR = Path(__file__).resolve().parent

_DTYPE_NAME = {0: "fp16", 1: "bf16", 2: "fp32"}
_DTYPE_EXPR = {0: "DType.float16", 1: "DType.bfloat16", 2: "DType.float32"}


def call_update(args: tuple) -> None:
    """JIT-compile (if needed) and dispatch a single update call."""
    config = _config_from_args(args)
    variant_fn, ctx_handle = _get_variant_fn(config)
    # Tack ctx_handle on as the 30th positional arg — the variant
    # entry point destructures `args[29]` for it.
    variant_fn(*args, ctx_handle)


def _config_from_args(args: tuple) -> tuple:
    return (
        args[22],  # dtype_code
        args[24],  # width
        bool(args[20]),  # has_bias
        bool(args[21]),  # apply_silu
        bool(args[25]),  # has_state_indices
        bool(args[27]),  # is_circular
    )


def _mod_name(config: tuple) -> str:
    (dt, w, hb, silu, hi, circ) = config
    return (
        f"{_DTYPE_NAME[dt]}_w{w}"
        f"_hb{int(hb)}_silu{int(silu)}_hi{int(hi)}_circ{int(circ)}"
    )


@lru_cache(maxsize=None)
def _get_variant_fn(config: tuple):
    import sys

    mod_name = _mod_name(config)
    # `kernel.mojo` imports `_silu_f32` from `common.mojo`, so we must
    # symlink the latter even though the variant template never touches
    # it directly.
    fn = compile_and_load_variant(
        subpkg="update",
        source_dir=_UPDATE_DIR,
        shared_files=("kernel.mojo", "common.mojo", "launch.mojo"),
        mod_name=mod_name,
        variant_source=_generate_variant_source(mod_name, config),
        entry_point_name="causal_conv1d_update_variant",
    )
    # The shared loader stashes the loaded variant module in
    # sys.modules so we can grab the one-shot ctx-handle helper without
    # re-importing the .so.
    module = sys.modules[mod_name]
    acquire = getattr(module, "causal_conv1d_update_acquire_ctx")
    ctx_handle = int(acquire(()))
    return fn, ctx_handle


def _generate_variant_source(mod_name: str, config: tuple) -> str:
    (
        dtype_code,
        width,
        has_bias,
        apply_silu,
        has_state_indices,
        is_circular,
    ) = config
    return f'''\
"""JIT-generated variant for causal_conv1d_update (config-frozen).

Generated by causal_conv1d_mojo.update._jit; do not hand-edit.
Module: {mod_name}
"""

from std.os import abort
from std.python import PythonObject
from std.python.bindings import PythonModuleBuilder

from launch import launch_update, acquire_ctx_handle


def causal_conv1d_update_acquire_ctx(
    mut py_self: PythonObject,
    mut args: PythonObject,
) raises -> PythonObject:
    """Create + retain a process-lifetime DeviceContext.

    Called once per variant from the Python side; the returned address
    is reused for every subsequent `causal_conv1d_update_variant` call.
    """
    var addr: Int = acquire_ctx_handle()
    return PythonObject(addr)


def causal_conv1d_update_variant(
    mut py_self: PythonObject,
    mut args: PythonObject,
) raises -> PythonObject:
    var x_addr: Int = Int(py=args[0])
    var w_addr: Int = Int(py=args[1])
    var b_addr: Int = Int(py=args[2])
    var state_addr: Int = Int(py=args[3])
    var o_addr: Int = Int(py=args[4])
    var batch_int: Int = Int(py=args[5])
    var dim_int: Int = Int(py=args[6])
    var seqlen_int: Int = Int(py=args[7])
    var state_len_int: Int = Int(py=args[8])
    var x_b_stride: Int = Int(py=args[9])
    var x_c_stride: Int = Int(py=args[10])
    var x_l_stride: Int = Int(py=args[11])
    var w_c_stride: Int = Int(py=args[12])
    var w_w_stride: Int = Int(py=args[13])
    var state_b_stride: Int = Int(py=args[14])
    var state_c_stride: Int = Int(py=args[15])
    var state_l_stride: Int = Int(py=args[16])
    var o_b_stride: Int = Int(py=args[17])
    var o_c_stride: Int = Int(py=args[18])
    var o_l_stride: Int = Int(py=args[19])
    var stream_handle_addr: Int = Int(py=args[23])
    var state_indices_addr: Int = Int(py=args[26])
    var cache_seqlens_addr: Int = Int(py=args[28])
    var ctx_handle_addr: Int = Int(py=args[29])

    if batch_int == 0 or dim_int == 0:
        return PythonObject(None)

    launch_update[
        {_DTYPE_EXPR[dtype_code]},
        {width},
        {has_bias},
        {apply_silu},
        {has_state_indices},
        {is_circular},
    ](
        batch_int,
        dim_int,
        seqlen_int,
        state_len_int,
        x_addr,
        w_addr,
        b_addr,
        state_addr,
        o_addr,
        state_indices_addr,
        cache_seqlens_addr,
        x_b_stride,
        x_c_stride,
        x_l_stride,
        w_c_stride,
        w_w_stride,
        state_b_stride,
        state_c_stride,
        state_l_stride,
        o_b_stride,
        o_c_stride,
        o_l_stride,
        stream_handle_addr,
        ctx_handle_addr,
    )
    return PythonObject(None)


@export
def PyInit_{mod_name}() -> PythonObject:
    try:
        var m = PythonModuleBuilder("{mod_name}")
        m.def_py_function[causal_conv1d_update_variant]("causal_conv1d_update_variant")
        m.def_py_function[causal_conv1d_update_acquire_ctx]("causal_conv1d_update_acquire_ctx")
        return m.finalize()
    except e:
        abort(String("failed to create Python module: ", e))
'''
